// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace wellcomePGSEZ.Models;

public partial class Model
{
    public byte MId { get; set; }

    public string MName { get; set; }

    public string MBrand { get; set; }

    public int MTypeId { get; set; }

    public virtual Types MType { get; set; }

    public virtual ICollection<Phone> Phones { get; set; } = new List<Phone>();
}