// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace wellcomePGSEZ.Models;

public partial class PgsezServicesContext : DbContext
{
    public PgsezServicesContext(DbContextOptions<PgsezServicesContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Department> Departments { get; set; }

    public virtual DbSet<Phone> Phones { get; set; }

    public virtual DbSet<Software> Softwares { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("Latin1_General_100_CI_AS_KS_SC_UTF8");

        modelBuilder.Entity<Department>(entity =>
        {
            entity.ToTable("department");

            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("id");
            entity.Property(e => e.DName)
                .HasMaxLength(50)
                .HasColumnName("dName");
        });

        modelBuilder.Entity<Phone>(entity =>
        {
            entity.ToTable("phones");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.PCode)
                .HasMaxLength(6)
                .IsUnicode(false)
                .HasColumnName("pCode");
            entity.Property(e => e.PDep).HasColumnName("pDep");
            entity.Property(e => e.PName)
                .HasMaxLength(60)
                .HasColumnName("pName");
            entity.Property(e => e.PSerial)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("pSerial");
            entity.Property(e => e.PhoneNumber)
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("phoneNumber");
            entity.Property(e => e.PropertyNumber).HasColumnName("propertyNumber");

            entity.HasOne(d => d.PDepNavigation).WithMany(p => p.Phones)
                .HasForeignKey(d => d.PDep)
                .HasConstraintName("FK_phones_department");
        });

        modelBuilder.Entity<Software>(entity =>
        {
            entity.ToTable("softwares");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.SAddress)
                .HasMaxLength(100)
                .HasColumnName("sAddress");
            entity.Property(e => e.SExplain)
                .HasMaxLength(50)
                .HasColumnName("sExplain");
            entity.Property(e => e.SImagePath)
                .HasMaxLength(100)
                .HasColumnName("sImagePath");
            entity.Property(e => e.SName)
                .HasMaxLength(30)
                .HasColumnName("sName");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}