// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace wellcomePGSEZ.Models;

public partial class Phone
{
    public int PId { get; set; }

    public string PProperty { get; set; }

    public string PNumber { get; set; }

    public string PIpAddress { get; set; }

    public byte PModel { get; set; }

    public string PUser { get; set; }

    public virtual Model PModelNavigation { get; set; }

    public virtual User PUserNavigation { get; set; }
}