// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace wellcomePGSEZ.Models;

public partial class Software
{
    public short Id { get; set; }

    public string SName { get; set; }

    public string SImageAddress { get; set; }

    public string SDescription { get; set; }

    public string SLinkAddress { get; set; }

    public int STypeId { get; set; }

    public string STag { get; set; }

    public bool? SStatus { get; set; }

    public virtual Types SType { get; set; }
}