// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace wellcomePGSEZ.Models;

public partial class Software
{
    public short Id { get; set; }

    public string SName { get; set; }

    public string SAddress { get; set; }

    public string SImagePath { get; set; }

    public string SExplain { get; set; }
}