// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace wellcomePGSEZ.Models;

public partial class Types
{
    /// <summary>
    /// شناسه نوع
    /// </summary>
    public int TId { get; set; }

    public int TType { get; set; }

    public string TName { get; set; }

    public virtual ICollection<Model> Models { get; set; } = new List<Model>();

    public virtual ICollection<Software> Softwares { get; set; } = new List<Software>();
}