// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace wellcomePGSEZ.Models;

public partial class User
{
    public string UId { get; set; }

    public string UFirstName { get; set; }

    public string ULastName { get; set; }

    public string UPosition { get; set; }

    public int? UDepId { get; set; }

    public bool? UIsAdmin { get; set; }

    public virtual ICollection<Phone> Phones { get; set; } = new List<Phone>();

    public virtual Department UDep { get; set; }
}